### ISSUE TITLE
`fs.copyFile()` does not work with `/snapshot` paths

### ISSUE THREAD

**Issue by TooTallNate** [vercel/pkg#639] opened 2019-02-26 23:49 UTC
https://nodejs.org/api/fs.html#fs_fs_copyfile_src_dest_flags_callback

Example error:

```
{ Error: ENOENT: no such file or directory, copyfile '/snapshot/foo/bar/index.js.map' -> '/Cache/foo/bar/index.js.map'
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/snapshot/foo/bar/index.js.map',
  dest: '/Cache/foo/bar/index.js.map' }
```

**Comment by sorleone** [comment] 2019-05-05 15:04
I too have this bug and this is a temporary solution that works:

`writeFileSync(path, readFileSync(src), { flag: 'wx' });`

**Comment by jingsam** [comment] 2019-09-01 09:49
I encounter same issue when use `fs-extra` `copySync` function. pkg `4.2.6` work fine.

**Comment by timsuchanek** [comment] 2020-10-29 11:09
We have the same issue for the `prisma` CLI.

**Comment by jingsam** [comment] 2021-04-12 04:23
ops！ This issue does't resolve yet

**Comment by kamesh95** [comment] 2021-06-25 13:44
@TooTallNate  Is there an update on this issue? I am still facing this in pkg v5.2.1

**Comment by kamesh95** [comment] 2021-06-28 10:13
The same thing happens when using chmod function as well. It says:
```
ENOENT: no such file or directory, chmod [[PATH_TO_FILE]]
```

I checked the path using exists function and it returned true that file does exist. But in chmod the same path fails as ENOENT
```
console.warn("exists:::", fse.existsSync(SCRIPT_PATH));
fse.chmodSync(SCRIPT_PATH, "755");
```
Output of above lines:
```
exists::: true
Exception:  
ENOENT: no such file or directory, chmod [[SCRIPT_PATH]]
```

**Comment by jingsam** [comment] 2021-09-27 00:44
bump

**Comment by robertsLando** [comment] 2021-09-29 15:22
It could be because it's missing here: https://github.com/vercel/pkg/blob/main/prelude/bootstrap.js#L502

**Comment by jingsam** [comment] 2021-12-29 06:21
.

**Comment by robertsLando** [comment] 2021-12-29 07:59
@jingsam PR?

**Comment by AzazelloB** [comment] 2022-01-20 15:28
The workaround

```
async function copy(source, target) {
    // use stream pipe to reduce memory usage
    // when loading a large file into memory.
    const writeFileStream = fs.createWriteStream(target);
    const readFileStream = fs.createReadStream(source).pipe(writeFileStream);

    return new Promise(function(resolve, reject) {
        writeFileStream.on('finish', resolve);
        readFileStream.on('error', reject);
    });
}
```

**Comment by AzazelloB** [comment] 2022-01-20 15:30
@jingsam ^

**Comment by robertsLando** [comment] 2022-01-20 16:27
I already opened a pr to fix this: #1484

**Comment by jesec** [comment] 2022-01-28 00:13
dupe of #420.

**Closed by jesec** 2022-01-28 00:13 UTC
Labels: bug
