### ISSUE TITLE
Add --fetch CLI flag to download the binaries to the pkg-cache

### ISSUE THREAD

**Issue by TooTallNate** [vercel/pkg#429] opened 2018-05-24 02:11 UTC
I want to be able to do this, so that a later invocation of `RUN pkg` will already have the binaries pre-cached:

``` dockerfile
FROM mhart/alpine-node:10 as base
RUN yarn global add pkg
RUN yarn --fetch node10-alpine-x64
```

I realize that there's a separate `pkg-fetch` package but it's inconvenient to have to include both modules in the `devDependencies`, and since `pkg` already has the functionality, it might as well expose it.

**Comment by hipstersmoothie** [comment] 2021-03-23 16:43
duplicate of #292

**Closed by hipstersmoothie** 2021-03-23 16:43 UTC
