### ISSUE TITLE
Experimental modules loader option ignored

### ISSUE THREAD

**Issue by lsjroberts** [vercel/pkg#526] opened 2018-09-15 13:34 UTC
SSCCE - https://github.com/lsjroberts/pkg-esm-loader-sscce

Trying to use `pkg` with the `--loader` node option does not work as expected.

In the linked sscce running:

```
node --experimental-modules --loader ./loader.mjs ./index.mjs
```

Will correctly load the `other.mjs` file from the `not-other` specifier.

However, running:

```
pkg --out-dir dist --options experimental-modules,loader=./loader.mjs index.mjs
```

Errors with this output:

```
> pkg@4.3.4
> Targets not specified. Assuming:
  node10-linux-x64, node10-macos-x64, node10-win-x64
> Warning Cannot find module 'not-other' from '/dir/pkg-esm-loader-sscce'
  /dir/pkg-esm-loader-sscce/index.mjs
> Warning Failed to make bytecode node10-x64 for file /snapshot/pkg-esm-loader-sscce/index.mjs
> Warning Failed to make bytecode node10-x64 for file /snapshot/pkg-esm-loader-sscce/index.mjs
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\pkg-esm-loader-sscce\index.mjs
```

I've tried looking through the source code of `pkg` to figure out a fix, but no luck so far.

Related to #335.

**Comment by hipstersmoothie** [comment] 2021-03-25 00:01
closing duplicate of #782

**Closed by hipstersmoothie** 2021-03-25 00:01 UTC
