### ISSUE TITLE
Possibility to be compressed using upx

### ISSUE THREAD

**Issue by dio** [vercel/pkg#281] opened 2017-11-15 23:14 UTC
I found that if we try to compress the resulted executables using upx it will be failed: `Pkg: Error reading from file.` Is it possible to see what is the root cause?

Thanks!

**Comment by serkanp** [comment] 2017-11-16 14:51
i have the same problem with node 8.9.0 with pkg 4.3.0-beta1 using upx 3.94
both on macos, linux

**Comment by astefanutti** [comment] 2018-02-03 16:29
Same problem on Windows as well (pkg 4.3.0, upx 3.94).

**Comment by xiaqiubo** [comment] 2018-02-08 06:06
I hava a same problem.
Environment:
Windows7 x64
node v8.9.0
pkg 4.3.0
upx 3.94

on Windows shell , it's no problem ,but after upx compress on linux will this error.

**Comment by jampy** [comment] 2019-09-03 09:06
I **guess** pkg is unable to read the attached assets (modules, static files) that are stored in the binary itself. 

upx will probably uncompress the binary in memory (or on the fly) and pkg can't deal with the compressed data in the binary *file*.

Probably pkg would need to handle compression itself for this to work (no upx or similar).

**Comment by rozbo** [comment] 2019-10-11 08:49
+1

**Comment by nd0164** [comment] 2020-04-28 05:59
you may try a new toy[pkgx](https://github.com/irelance/node-pkgx)

**Comment by hipstersmoothie** [comment] 2021-03-23 16:33
duplicate of #121

**Closed by hipstersmoothie** 2021-03-23 16:33 UTC
