### ISSUE TITLE
Hide Terminal

### ISSUE THREAD

**Issue by RGFTheCoder** [vercel/pkg#520] opened 2018-09-07 01:02 UTC
I was wondering if there was a setting that would allow me to hide the terminal window and run it as a background process.

**Comment by Darkle** [comment] 2018-09-10 06:56
@RGFTheCoder Try this: https://github.com/s-h-a-d-o-w/create-nodew-exe

**Comment by silverkorn** [comment] 2018-11-02 22:35
On Windows, you can create a VBScript like this one :
```vbs
Dim objShell, objFSO, objFile, strArguments
Set objShell = WScript.CreateObject("WScript.shell")
Set objFSO = CreateObject("Scripting.FileSystemObject")
Set objFile = objFSO.GetFile(WScript.ScriptFullName)
For Each strArgument in WScript.Arguments
    strArguments = strArguments & " " & strArgument
Next
objShell.Run """" & objFSO.GetParentFolderName(objFile) & "\" & objFSO.GetBaseName(WScript.ScriptFullName) & ".exe""" & strArguments, 0, False
```

Just put it in the directory as the executable and give it the same name but with the `.vbs` extension and use this script instead for your potential desktop shortcut.

This suggestion might not work properly with quoted arguments. If so, you might want to include this instead if judged necessary : 
https://stackoverflow.com/questions/40056204/how-do-i-get-raw-vbscript-command-line-arguments#answer-40056793

**Comment by whiter001** [comment] 2019-01-17 09:22
use powershell like this:
```powershell
@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "example.exe"
```

**Comment by Simran-B** [comment] 2019-01-17 14:43
VBScript and Powershell may not be permitted to be used by the current user, or not be available at all.

**Comment by silverkorn** [comment] 2019-01-17 21:57
I suggested VBScript (WSH) for both legacy support (Windows XP and above) and technical standard for more advanced scripting when BATCH scripting is not enough.

Limitations are usually manually set by an administrator (GPOs) because it is stated that it is encouraged to be executed as a non-administrator user ([Reference](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wscript#remarks))

**Comment by LuHaikun** [comment] 2021-03-05 05:57
> I was wondering if there was a setting that would allow me to hide the terminal window and run it as a background process.

I also want to got the answer

**Comment by hipstersmoothie** [comment] 2021-03-23 17:10
duplicate of #135

**Closed by hipstersmoothie** 2021-03-23 17:10 UTC
