### ISSUE TITLE
ES6 Module does not compile properly with bytecode error

### ISSUE THREAD

**Issue by rfl890** [vercel/pkg#1592] opened 2022-04-18 22:28 UTC
### What version of pkg are you using?

5.6.0

### What version of Node.js are you using?

v17.9.0

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node17-win-x64

### Describe the Bug

When I try to compile a node.js project with "type: module", it produces this error:
```
> Warning Babel parse has failed: 'await' is only allowed within async functions and at the top levels of modules. (262:12)
> Warning Failed to make bytecode node17-x64 for file C:\snapshot\console\index.js
```
In my package.json:
```json
{
  "name": "consoledsl",
  "version": "1.0.0",
  "main": "index.js",
  "type": "module",
  "license": "MIT",
  "dependencies": {
    "axios": "^0.26.1",
    "chalk": "^5.0.1",
    "cli-progress": "^3.10.0",
    "readline-sync": "^1.4.10",
    "synchronous-sleep": "^1.0.4"
  },
  "pkg": {
    "options": [
      "experimental-modules"
    ]
  }
}
```

### Expected Behavior

It compiles properly and the Babel error is removed since it is a module.

### To Reproduce

Create an node.js project with 
```json
{
  "type": "module",
  "pkg": {
    "options": [
      "experimental-modules"
    ]
  }
}
```
**included** in the package.json and use ES6 features like top level await, imports etc...
Then compile with `pkg -t node17-win-x64 [filename].js`

**Comment by draeder** [comment] 2022-04-24 17:02
Running into this very issue with MacOS. It appears to be a problem with es6 modules with any platform target.

**Comment by grahamgraham** [comment] 2022-05-06 00:29
As @draeder said, it's an incompatibility issue with ES6. This issue is known by the devs, but is still not fixed. You either have to write it in ES5 syntax or use a different app.

**Comment by robertsLando** [comment] 2022-05-06 06:36
Duplicate of https://github.com/vercel/pkg/issues/1291

**Closed by robertsLando** 2022-05-06 06:36 UTC

**Comment by rfl890** [comment] 2022-05-06 19:16
Just use webpack. Fine with me
