### ISSUE TITLE
Unexpected token 'export' - lodash-es (Failed to make bytecode)

### ISSUE THREAD

**Issue by lbertoncello** [vercel/pkg#976] opened 2020-09-14 20:28 UTC
After running the following command using pkg 4.4.9

`pkg -t node12-win .\src\app.js --debug`

 I've got the following error:

>E:\snapshot\upbotswa\node_modules\typescript-parser\node_modules\lodash-es\lodash.js:10
export { default as add } from './add.js';
^^^^^^

>SyntaxError: Unexpected token 'export'
    at new Script (vm.js:89:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
>E:\snapshot\upbotswa\node_modules\typescript-parser\node_modules\lodash-es\lodash.js:10
export { default as add } from './add.js';
^^^^^^

>SyntaxError: Unexpected token 'export'
    at new Script (vm.js:89:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
> Warning Failed to make bytecode node12-x64 for file E:\snapshot\upbotswa\node_modules\typescript-parser\node_modules\lodash-es\lodash.js

I'm using Node 12.18.3 on Windows. I think it's an issue related to es6 modules. I've tried many solutions and workarounds that I read on old Issues (without solution), but none of them has worked. Someone have a workaround to help me?

**Comment by matheusm821** [comment] 2020-10-18 02:57
same error here

**Comment by bo-516** [comment] 2021-03-04 03:55
same error...

**Comment by hipstersmoothie** [comment] 2021-03-04 04:08
Pkg currently doesn support import/export via native node js modules. There's a few things that need to happen to make it possible:

1. Update pkg-fetch with newer node releases that include the inflated support 
2. Changes to pkg to detect "type: module" and bundle the code using modules instead of requires

**Comment by hipstersmoothie** [comment] 2021-03-25 00:01
Closing because this is a dupe of #782

**Closed by hipstersmoothie** 2021-03-25 00:01 UTC

**Comment by pxim** [comment] 2021-08-13 02:51
same error here
