### ISSUE TITLE
Is it possible to unpack a pkg compiled execute?

### ISSUE THREAD

**Issue by ExtendLord** [vercel/pkg#340] opened 2018-02-01 16:39 UTC

**Comment by J05HI** [comment] 2018-02-07 17:11
@ExtendLord
I think you can't decompile a exe

**Comment by ExtendLord** [comment] 2018-02-07 17:56
@J05HI It depends

You can decompile a .NET exe

And also you can do the same to executes that were created by pkg.

It is possible to view pkg(exe) files using a hex editor and you will be able to see the source code.

**Comment by J05HI** [comment] 2018-02-07 18:39
@ExtendLord
Oh really. I can't see the real source if doing that. Only hex...

**Comment by ExtendLord** [comment] 2018-02-07 18:54
@J05HI If you go to a specific line, you will see the js code(Make sure that you use a hex editor that translate to letters :|)

So the JS is still visible.

You can try to search to get to that section(Where the JS code is).

**Comment by J05HI** [comment] 2018-02-07 21:27
@ExtendLord
Which line 😅

**Comment by ExtendLord** [comment] 2018-02-07 21:34
@J05HI You need to find that line, it is different for each pkg(exe)

You can do that by searching(Ctrl+F)

For example search `"dependencies": {` . (There are more package.json's than one because the modules are also inside the pkg but the first result should be the right json)

The code itself is somewhere around.

**Comment by J05HI** [comment] 2018-02-08 05:24
@ExtendLord
Okay thanks! :)

**Comment by dcerisano** [comment] 2018-04-19 10:45
All public package source is included in the binary.

According to issue #194 you need to privatise your package manifest in order prevent your source from being included in the binary.

AFAIK, private packages are stored as tokenized V8 compilations.

**Comment by nubuntu** [comment] 2020-09-04 03:46
![image](https://user-images.githubusercontent.com/1622745/92197362-bc9d7a00-ee9b-11ea-97c6-cfc92fb8715e.png)
So bad, you can read the js source clearly, how can we avoid this?

**Comment by nouvist** [comment] 2020-10-22 07:33
Pass `-d` to pkg command line to see if a file was placed with source code or not. As as rule, `node_modules` goes with sources as there are permissive licenses and no `private: true` in packages there. Top-level code (your code) goes without source if you use `private: true`

_Originally posted by @igorklopov in https://github.com/vercel/pkg/issues/194#issuecomment-322138139_

@nubuntu only node_modules goes with sources, your code will compiled. I tried some test, yes it's compiled, except string variable. But, I think it's still hard to reverse engineering it.

**Comment by hipstersmoothie** [comment] 2021-03-23 16:40
Duplicate of #328

**Closed by hipstersmoothie** 2021-03-23 16:40 UTC
