### ISSUE TITLE
Error! Unexpected token (1:0)

### ISSUE THREAD

**Issue by pdhar-tibco** [vercel/pkg#395] opened 2018-04-08 07:23 UTC
I am getting this error when I use this command line
```
pkg  -t node9-alpine-x64 -o ./app.linux .
....
> Error! Unexpected token (1:0)
  /src/dist/server/node_modules/ipaddr.js/.npmignore
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
When I use this command line
```
pkg  -t node9-alpine-x64 -o ./app.linux ./main.js
```
I get the executable but it does not snapshot the assets.
The pkg config looks like this
```
"pkg": {
        "scripts": [
            "**/*.js"
        ],
        "assets": [
            "../client/**/*",
            "**/*.json"
        ]
    },
```

**Comment by motin** [comment] 2018-10-18 19:10
This seems to be a duplicate of https://github.com/zeit/pkg/issues/317

**Comment by hipstersmoothie** [comment] 2021-03-23 16:50
closing dupe

**Closed by hipstersmoothie** 2021-03-23 16:50 UTC
