### ISSUE TITLE
pkg can't pack other local js file but entry file

### ISSUE THREAD

**Issue by wrjcs** [vercel/pkg#691] opened 2019-05-23 07:17 UTC
Hello,
I use pkg to pack my project, and I copy the executable file to other pc, it can't executer.
It has error"Cannot find module './controllers/customer.js'", the customer.js is my code file.
how to resove this probleme?

Thanks.

**Comment by sharathbaddam** [comment] 2019-05-29 16:46
I had same problem, i packaged up all the local files into a node_module and required it in main file.

**Comment by lselden** [comment] 2019-05-30 14:57
If your code isn't getting detected it's probably because you're dynamically requiring your files. You can add them into the ['scripts' config option](https://github.com/zeit/pkg#scripts)

**Comment by hipstersmoothie** [comment] 2021-03-24 23:22
No reproduction repo and it's been a year since updates. Closing, feel free to open a new issue with a reproduction repo if the problem still exists!

**Closed by hipstersmoothie** 2021-03-24 23:22 UTC
