### ISSUE TITLE
how to build node12.2.0-linux-armv7

### ISSUE THREAD

**Issue by JoahTheron** [vercel/pkg#1017] opened 2020-12-23 13:35 UTC
pkg . -t node12.2.0-linux-armv7 --output dist/Linux
> pkg@4.4.9
> Fetching base Node.js binaries to PKG_CACHE_PATH

> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.2.0-win-armv7
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-win-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-win-armv7"}
> Building base binary from source:
  built-v12.2.0-win-armv7
> Error! Not able to build for 'armv7' here, only for 'x64'
`

i don't get it why it always tries to fetch win binaries.

**Comment by fcastilloec** [comment] 2021-01-02 05:38
I think your problem, which is probably a bug, is specifying the current directory (i.e. `.`) before the `-t` option. Move that to the end, or even better use: `pkg -t node12.2.0-linux-armv7 -o dist/Linux package.json` That's how I use it and it works without any problems.

**Comment by zaherg** [comment] 2021-01-03 08:51
To build ARM arch distribution of your application you need to do it on an ARM device like Raspberry PI or something on the cloud.

since you are on `X64` arch device you can only target `x64` arch OSs.

hope this help

**Comment by kdolan** [comment] 2021-02-27 18:57
When trying to build on a RPi this is what I am getting. Stays at 0% forever:
Compiling Node.js from sources...
  make                         [                    ] 0%

**Comment by cupcakearmy** [comment] 2021-03-25 08:51
btw it's a duplicate of https://github.com/vercel/pkg/issues/969 i believe :)

**Comment by robertsLando** [comment] 2021-03-26 13:20
This should be fixed in 4.5.0

**Closed by robertsLando** 2021-03-26 13:20 UTC
