### ISSUE TITLE
Console window

### ISSUE THREAD

**Issue by Admiral-Enigma** [vercel/pkg#306] opened 2017-12-13 18:00 UTC
How do I prevent a console window opening when I run my exe?

**Comment by claytonaalves** [comment] 2017-12-29 11:41
Nodejs always opens a console window. This behavior is related to the target image and you can't change it unless you recompile the target image with this option disabled.

Nonetheless, this link has some nice insights to workaround this: http://www.robvanderwoude.com/battech_hideconsole.php

**Comment by BernardoLaing** [comment] 2018-12-14 01:36
Having the node application, what options can I set so the console windows does not show?

**Comment by staafl** [comment] 2019-11-22 14:54
@BernardoLaing , on Windows, you can set a flag on the exe to ensure it runs without a console window:

`editbin /subsystem:windows myprogram.exe`

editbin on my machine is located at c:\program files (x86)\microsoft visual studio\2019\Preview\VC\Tools\MSVC\14.20.27508\bin\Hostx86\x86\editbin.exe (I'm using VS 2019)

Note running the edited app in through a console will not produce output unless you explicitly pipe it (e.g. myprogram.exe | type)

**Comment by hipstersmoothie** [comment] 2021-03-23 17:00
duplicate of #135

**Closed by hipstersmoothie** 2021-03-23 17:00 UTC

**Comment by mcuong223** [comment] 2023-05-15 06:28
> @BernardoLaing , on Windows, you can set a flag on the exe to ensure it runs without a console window:
> 
> `editbin /subsystem:windows myprogram.exe`
> 
> editbin on my machine is located at c:\program files (x86)\microsoft visual studio\2019\Preview\VC\Tools\MSVC\14.20.27508\bin\Hostx86\x86\editbin.exe (I'm using VS 2019)
> 
> Note running the edited app in through a console will not produce output unless you explicitly pipe it (e.g. myprogram.exe | type)

It works perfectly for me, thank you dude!
