### ISSUE TITLE
Can i package electron app?

### ISSUE THREAD

**Issue by Nisthar** [vercel/pkg#325] opened 2018-01-11 09:07 UTC
Can i package electron app? Is it possible to decompile the app and get the code?

**Comment by BenGermany** [comment] 2018-01-24 09:10
Packing electron would be the next great thing - I am hoping for the future, too ;-)

But, by the way, with professional tools, every code can be decompiled, often as relative cryptic code, but hidden things can be unhidden. But - that's more for very professionals than standard users ;-)

**Comment by jingsam** [comment] 2018-01-24 10:30
Use electron-packager

**Comment by lgoudriaan** [comment] 2018-04-20 13:26
this is a duplicate of #52

**Comment by yakirzana** [comment] 2019-04-16 08:30
> Use electron-packager

Not enough. In electron-packager the source files are visible.

**Closed** 2021-03-23 16:41 UTC
