### ISSUE TITLE
Error: require('fs').readdirSync( "/", { encoding: "utf8", withFileTypes: true } )

### ISSUE THREAD

**Issue by la9527** [vercel/pkg#938] opened 2020-06-26 08:55 UTC
`pkg` problem has been found. Please solve this problem.
   
  - my system is 'macOS catalina 10.15.3'.
  - node 12.16.3
  - pkg version 4.4.8

code)
```
require('fs').readdirSync( "/", { encoding: "utf8", withFileTypes: true }
```

exception)

```
pkg/prelude/bootstrap.js:776
      if (entity[STORE_BLOB] || entity[STORE_CONTENT]) return new Dirent(entry, 1);
                ^

TypeError: Cannot read property '0' of undefined
    at pkg/prelude/bootstrap.js:776:17
    at Array.map (<anonymous>)
    at getFileTypes (pkg/prelude/bootstrap.js:773:20)
    at Object.fs.readdirSync (pkg/prelude/bootstrap.js:841:42)
    at Object.<anonymous> (/snapshot/test_program/index.js:1:90)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
```

[issue_readdirSync_withFileType.zip](https://github.com/vercel/pkg/files/4835955/issue_readdirSync_withFileType.zip)

Thank you for making a good program.

**Comment by hjyssg** [comment] 2020-12-20 13:27
This bug happened on windows as well.
May I ask when this pull request will be merged?

**Comment by albanm** [comment] 2021-02-04 09:07
I looked at [this commit](https://github.com/vercel/pkg/pull/992/commits/b694d657af3e6c5dcaf6cc1efb60d9833152c580) from the pending pull request, and deduced that the problem is specific to reading root paths. Indeed, c:\ breaks but c:\test is ok.

Reviewing and merging the pull request would be greatly appreciated, it seems to provide a very straightforward fix.

**Comment by dverzolla** [comment] 2021-03-12 13:03
@albanm having the same trouble here on Windows. 
When reading from 'c:\' the error is trigged, when reading from 'c:\windows' works smoothly. 

I know the guys from vercel are freaking busy, however, would some one take attention for this bug?

@igorklopov @leo @robertsLando

**Comment by robertsLando** [comment] 2021-03-12 14:19
@dverzolla I'm not a maintainer, @leerob could you give a look at https://github.com/vercel/pkg/pull/992

**Comment by leerob** [comment] 2021-03-12 16:59
Thanks, I've just merged the PR. https://github.com/vercel/pkg/pull/992

To clarify, we are looking for maintainers of this package! I'm helping answer things in my free time. If you'd be interested in helping maintain, please message me!

**Closed by leerob** 2021-03-12 16:59 UTC
