### ISSUE TITLE
Spread operator is not suported

### ISSUE THREAD

**Issue by thiagofernando** [vercel/pkg#352] opened 2018-02-14 23:22 UTC
Hi, 
in my code i have this 
`module.exports = {...defaultConfig, ...environment};`

when I try to compile I get the following message

> Unexpected token

**Comment by ashking** [comment] 2018-02-20 15:05
Yeah, am having the same issue too. I suspected it could be the node issue. But it looks like pkg issue. @igorklopov any idea why?

**Comment by jflayhart** [comment] 2018-02-23 15:05
How are you transpiling ES6 -> ES5? [Node supports some ES6 syntax](http://node.green/#ES2018-features-object-rest-spread-properties-object-spread-properties), but not all, so which version of node are you using?

Personally, I use webpack to babelfy the code prior to using pkg to avoid these sort of things.

**Comment by ashking** [comment] 2018-02-26 07:47
> Don't think this is a pkg issue per se. How are you transpiling ES6 -> ES5? Node supports some ES6 syntax, but not all, so which version of node are you using?

Using the latest LST version v8.9.4. 

Node v8.9.4 supports use of spread operator without need of transpiling the code. Not sure why pkg would not?

**Comment by jflayhart** [comment] 2018-02-26 14:05
Not sure, maybe something in how the binaries are packaged... again, I use webpack/babel to compress/transpile my code and then run pkg.

**Comment by kalinkrustev** [comment] 2018-02-27 04:00
Duplicate of #206

**Comment by ramiel** [comment] 2018-02-27 14:46
I don't see why we should use babel/webpack to transpile code which doesn't need to be transpiled. In my backend only projects I carefully avoid to use unsupported syntax just not to install other dependencies as webpack/babel etc. This should be considered a pkg issue, since it should do any supposition about how a user organize his project.

**Comment by hipstersmoothie** [comment] 2021-03-23 16:45
If you want to use spread and target a node that doesn't support it you should use babel. Otherwise just use a version of node that supports the JS features you want

**Closed by hipstersmoothie** 2021-03-23 16:45 UTC
