### ISSUE TITLE
Is it possible to not showing the console on Windows

### ISSUE THREAD

**Issue by kaeyonbaker** [vercel/pkg#427] opened 2018-05-23 12:45 UTC
I want the program just run in the background, simply not showing the annoying console window.
I wonder if  there is an options I can set while packaging, but I can't find any in README.
Any help would be appreciated!

**Comment by rohit5ram** [comment] 2018-07-13 07:35
Use a VBS Script to call the batch file:

Set WshShell = CreateObject("WScript.Shell")
WshShell.Run chr(34) & "C:\path\to\your\batchfile.bat" & Chr(34), 0
Set WshShell = Nothing

Copy the lines above to an editor and save the file with .VBS extension.

**Comment by sebastienmamy** [comment] 2020-02-22 23:27
hello there,

I have the same question on Mac: we have a very elegant single file app, but unfortunately an ugly console window (useless unless for debug) pops up.

I did not see any open issue or pull requests on that subject, should I create one?

thanks in advance

**Comment by sebastienmamy** [comment] 2020-03-06 07:26
> hello there,
> 
> I have the same question on Mac: we have a very elegant single file app, but unfortunately an ugly console window (useless unless for debug) pops up.
> 
> I did not see any open issue or pull requests on that subject, should I create one?
> 
> thanks in advance

Actually, there is no need, as far as the result file is packaged into a MacOS .app directory. A complete description of the Mac OS bundle is available in the _Anatomy of a macOS Application Bundle_ section of [Apple dedicated documentation](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1) 

Once done, to avoid the display of the console window, set 
```
<key>LSBackgroundOnly</key>
<string>true</string>
```
in the Info.plist file of your bundle

note: this will prevent the display of the app icon in the Docker, so the only way to stop the app is to go to the task manager or to use kill command in Term

**Comment by hipstersmoothie** [comment] 2021-03-23 16:59
duplicate of #135

**Closed by hipstersmoothie** 2021-03-23 16:59 UTC
