### ISSUE TITLE
flag `--options r=esm` changed the behavior of packaging.

### ISSUE THREAD

**Issue by Losses** [vercel/pkg#727] opened 2019-06-28 14:26 UTC
Packing the same project, without the `--options r=esm`, the output is:

![image](https://user-images.githubusercontent.com/1384036/60349137-948ecd00-99f3-11e9-9308-1ac19e1007bb.png)

but the same code base, if i add the flag, a bunch of things will appear...

![image](https://user-images.githubusercontent.com/1384036/60349203-b7b97c80-99f3-11e9-8887-7c4905869235.png)
...
![image](https://user-images.githubusercontent.com/1384036/60349262-cef86a00-99f3-11e9-8191-33d14a9529e9.png)

I think it's a bug...

**Comment by hipstersmoothie** [comment] 2021-03-25 00:02
closing duplicate of #782

**Closed by hipstersmoothie** 2021-03-25 00:02 UTC
