### ISSUE TITLE
Possible to exclude files?

### ISSUE THREAD

**Issue by scaszoo** [vercel/pkg#383] opened 2018-03-23 13:55 UTC
The folder may contain files not intended to be packed along with the important files. Does pkg have an option to ignore files or could it use .gitignore to learn which files to ignore?

**Comment by kamleshkarwande** [comment] 2019-05-10 10:51
any way to do this?

**Comment by pedrodaher1997** [comment] 2019-06-18 18:36
Help.

**Comment by anseki** [comment] 2020-08-06 03:23
Hi, thank you for the very great tool!

I also need an option that excludes files.
Or, selecting files like Tree Shaking of JS packer such as Webpack is better.
I want to use Google Firebase but the library is very big. That contains all sub products but I want only one product.

**Comment by olaven** [comment] 2021-01-15 10:13
Thumbs up for this 👍

**Comment by hipstersmoothie** [comment] 2021-03-23 16:49
duplicate of #313

**Closed by hipstersmoothie** 2021-03-23 16:49 UTC
