### ISSUE TITLE
[Error] Nightmare Js times out

### ISSUE THREAD

**Issue by cjay567** [vercel/pkg#374] opened 2018-03-15 20:43 UTC
Hiya! I've been trying to compile a node program that does some web scraping in Nightmare Js and it runs fine when run in Node 8.0.0 on Windows 10 x64, but when I compile it with `-t node8-win-x64` or `-t node8-win` I get this error: 
```
Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?
    at Timeout._onTimeout (C:\snapshot\project\node_modules\nightmare\lib\actions.js:634:7)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```
The code: 
```
const Nightmare = require('nightmare');
const nightmare = new Nightmare({gotoTimeout: 1200000}); // The problem still persists whether or not options are included here

module.exports = async (city) => {
    let window = await Promise.resolve(
        nightmare 
            .goto(`https://www.google.com/search?q=${encodeURIComponent(city)}+weather`, {"Accept-Language": "fr"})
            .evaluate(function () {
                return window;
            })
            .end()
    )
    return window;
}
```
The `assets` property of `pkg` in package.json contains the path to a copy of JQuery.
Any help would be appreciated. Thanks!

P.S. Yes I know there are weather APIs I can use but I need this specific data.

**Comment by bodyajoy** [comment] 2020-07-01 17:02
hello!
did u solve that?

**Comment by cjay567** [comment] 2020-07-01 17:26
hi! it's been a while since i've worked on this project. i don't think i ever managed to fix this issue; i think i learned it had something to do with my internet connection and then i tried it on a different computer and it worked. sorry. maybe try figuring out how to extend the length of self.options.executionTimeout in nightmare\lib\actions.js? that's the only thing i can think of

**Comment by bodyajoy** [comment] 2020-07-01 17:31
> hi! it's been a while since i've worked on this project. i don't think i ever managed to fix this issue; i think i learned it had something to do with my internet connection and then i tried it on a different computer and it worked. sorry. maybe try figuring out how to extend the length of self.options.executionTimeout in nightmare\lib\actions.js? that's the only thing i can think of

well.. my internet connection is well
compilled program after pkg with nightmare don't want to nightmare.evalute - always timeout

**Comment by hipstersmoothie** [comment] 2021-03-23 16:51
duplicate of #188

**Closed by hipstersmoothie** 2021-03-23 16:51 UTC
