### ISSUE TITLE
Issue with packaging Nightmare.js

### ISSUE THREAD

**Issue by relixj** [vercel/pkg#397] opened 2018-04-09 06:01 UTC
Hello, 
I'm facing the below issue while packaging nightmare.js. I'm using pkg version 4.3.1

pkg app.js -t node8-win-x64
> pkg@4.3.1
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  node_modules/nightmare/lib/runner.js
  path-to-executable/nightmare/runner.js
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  node_modules/nightmare/lib/frame-manager.js
  path-to-executable/nightmare/frame-manager.js
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  node_modules/nightmare/lib/ipc.js
  path-to-executable/nightmare/ipc.js
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  node_modules/nightmare/lib/preload.js
  path-to-executable/nightmare/preload.js
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  node_modules/electron/dist
  path-to-executable/electron/dist
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  node_modules/sliced/index.js
  path-to-executable/node_modules/sliced/index.js
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  node_modules/deep-defaults/lib/index.js
  path-to-executable/node_modules/deep-defaults/index.js

I have tried creating nightmare and electron folders in the same path where the executable is getting created, copied the required files under these folders. Facing the issue even after that.

How do I find out where 'path-to-executable' is pointing to? I assume it is the current directory.

Current directory contents...

ls -la
drwxr-xr-x 16 300024394 506075219 544 Apr 6 00:04 .
drwxr-xr-x 11 300024394 506075219 374 Apr 5 23:26 ..
-rw-r--r--@ 1 300024394 506075219 8196 Apr 5 15:47 .DS_Store
drwxr-xr-x 6 300024394 506075219 204 Mar 30 15:46 .idea
-rw-r--r-- 1 300024394 506075219 35602655 Apr 6 00:04 app.exe
-rw-r--r-- 1 300024394 506075219 1311 Apr 4 10:33 app.js
drwxr-xr-x 3 300024394 506075219 102 Mar 23 14:40 bin
drwxr-xr-x 3 300024394 506075219 102 Apr 5 23:45 electron
drwxr-xr-x 4 300024394 506075219 136 Apr 5 23:52 exe
drwxr-xr-x 9 300024394 506075219 306 Apr 5 23:35 nightmare
drwxr-xr-x 291 300024394 506075219 9894 Apr 5 23:57 node_modules
-rw-r--r-- 1 300024394 506075219 93492 Apr 5 23:56 package-lock.json
-rw-r--r-- 1 300024394 506075219 604 Apr 5 23:56 package.json
drwxr-xr-x 6 300024394 506075219 204 Apr 5 15:47 public
drwxr-xr-x 4 300024394 506075219 136 Mar 26 12:23 routes
drwxr-xr-x 5 300024394 506075219 170 Mar 23 16:31 views

Regards,
Relix

**Comment by gumpjt** [comment] 2018-07-04 08:13
HI, did you solve this? I'm facing the same problem.

**Comment by yacinsantos** [comment] 2018-11-24 23:17
same problem here !

**Comment by anlexN** [comment] 2019-06-12 13:07
same problem here!

**Comment by hipstersmoothie** [comment] 2021-03-23 16:48
duplicate of #188

**Closed by hipstersmoothie** 2021-03-23 16:48 UTC
