### ISSUE TITLE
Warning Failed to make bytecode for file 

### ISSUE THREAD

**Issue by Deilan** [vercel/pkg#310] opened 2017-12-21 02:52 UTC
Trying to package an app with just `--targets node8.6.0-win-x86` in linux. Get dozens of warnings:
`Warning Failed to make bytecode for file C:\snapshot\app\index.js error (spawn /home/travis/.pkg-cache/v2.3/fetched-v8.6.0-linux-x86 ENOENT)`.

The resulting app doesn't work on Windows.

If i enable `--no-bytecode`, I get:
> Error! --no-bytecode and no source breaks final executable
> /home/travis/build/app/index.js
> Please run with "-d" and without "--no-bytecode" first, and make
> sure that debug log does not contain "was included as bytecode".

With the option disabled and `-d` enabled I get around one hundred lines with `[debug] The file was included as bytecode (no sources)` in the logs.

If I launch the same packaging process in macOS, it works fine.

Both `pkg@4.2.6` or `pkg@4.3.0-beta.5`.

**Comment by adonespitogo** [comment] 2017-12-24 02:09
Using pkg@4.2.6 - I also get many errors `> Warning Failed to make bytecode node8.0.0-armv7 for file /snapshot/piso-wifi/node_modules/engine.io-client/node_modules/ws/lib/BufferUtil.fallback.js error (read ECONNRESET)` when trying to compile with `--targets node8.0.0-linux-armv7`

I'm on arch linux

**Comment by niicojs** [comment] 2017-12-27 16:00
I got the same trying to build for windows x86 from travis

**Comment by adonespitogo** [comment] 2017-12-27 22:11
@zeit If you can let us know where to start looking into this issue, I'd be very much happy to help fix this.

**Comment by itai-codefresh** [comment] 2018-01-07 11:15
This is really a blocker for me too.
Our CI generates the binaries and it is currently broken.
Any workaround until the fix would be appreciated.

**Comment by niicojs** [comment] 2018-01-07 14:23
As a workaround, you can use a ci tool based on windows (like appveyor) which doesn't have the problem. It's free for open source so that works for me in the meantime.

**Comment by Deilan** [comment] 2018-01-07 14:40
Continuing @niicojs's note. If in your case Travis CI is a must, consider switching from linux vm or container to macos vm, which works pretty fine. We've done this in our project.

Pros: pretty little changes towards already existing build workflow.
Cons: macos vm starts up much longer than linux containers.

**Comment by niicojs** [comment] 2018-01-07 14:50
good point
for now, I've kept everything else in travis/linux and moved packaging only to appveyor so I keep travis fast (which is good) and move packaging (which can be slower) elsewhere

**Comment by egoroof** [comment] 2018-01-21 09:18
Have the same problem.
As our private CI is only on linux so we goes this way: bundle all js files into single one with webpack and deploy this bundle with nodejs binary from official website (like https://nodejs.org/dist/v8.9.4/win-x86/node.exe). Maybe it help someone.

**Comment by mjackson** [comment] 2018-01-31 21:53
I ran into this same issue today trying to [build `react-stdio`](https://travis-ci.org/ReactTraining/react-stdio/builds/335840760) for x86 on Windows and Linux, using pkg 4.3.0.

**Comment by huerlisi** [comment] 2018-02-04 21:42
I experienced the same issue on GitLab CI. But I was able to build them locally. The solution was to include support for 32-bit executables.

I'm using the `node:7` image on GitLab CI as build image. The runners are on a 64-bit host. When  debugging locally using `docker run -it -v $PWD:/root/vdds-client node:7 /bin/bash` I found out that I had the same issue as on the CI: no proper win-x86 output.

Using the `-d` flag for `pkg` I saw the following section:
```
> [debug] Targets:
  [
  {
    "nodeRange": "node6",
    "platform": "win",
    "arch": "x86",
    "output": "/root/vdds-client/client.exe",
    "forceBuild": false,
    "fabricator": {
      "nodeRange": "node6",
      "platform": "linux",
      "arch": "x86",
      "forceBuild": false,
      "binaryPath": "/root/.pkg-cache/v2.5/fetched-v6.11.5-linux-x86"
    },
    "binaryPath": "/root/.pkg-cache/v2.5/fetched-v6.11.5-win-x86"
  }
]
```
When trying to run the `/root/.pkg-cache/v2.5/fetched-v6.11.5-linux-x86` it gave me the following error:
```
root@a2cd31593bb2:~/vdds-client# ls /root/.pkg-cache/v2.5/fetched-v6.11.5-linux-x86
/root/.pkg-cache/v2.5/fetched-v6.11.5-linux-x86
root@a2cd31593bb2:~/vdds-client# /root/.pkg-cache/v2.5/fetched-v6.11.5-linux-x86
bash: /root/.pkg-cache/v2.5/fetched-v6.11.5-linux-x86: No such file or directory
```
So I took a look:
```
root@a2cd31593bb2:~/vdds-client# file /root/.pkg-cache/v2.5/fetched-v6.11.5-linux-x86
/root/.pkg-cache/v2.5/fetched-v6.11.5-linux-x86: ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=ac11506dd30ec242b56788701d1315efeed93910, not stripped
```
This triggered the idea that I did include the `i386` support locally...

So I was able to fix it for my case (gitlab-ci, node:7 image) by installing glibc with i386 support by adding the following to the `.gitlab-ci.yml` `script` section:

```
    - dpkg --add-architecture i386
    - apt-get update
    - apt-get install -y libc6:i386 libstdc++6:i386
```

You might need to adapt for your setup;-) Installing `ia32-libs` instead of multiarch could be also a way, don't know about non-Debian systems...

**Comment by pionl** [comment] 2018-10-11 09:07
@huerlisi suggestions works perfectly! I've create node image with i386 installed - https://github.com/pionl/docker-node-with-i386

**Comment by Deilan** [comment] 2021-04-27 10:04
Still actual

**Comment by Deilan** [comment] 2021-04-27 10:05
> This issue is stale because it has been open 90 days with no activity. Remove the stale label or comment or this will be closed in 5 days. To ignore this issue entirely you can add the no-stale label

Still actual

**Comment by markus456** [comment] 2021-05-04 05:50
I'm seeing an odd error with pkg@5.1.0 when building on a aarch64 system:

```
> Warning Failed to make bytecode node10-arm64 for file /snapshot/maxctrl/maxctrl.js error (write EPIPE)
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at fabricate (/home/admin/MaxScale/_build/maxctrl/node_modules/pkg/lib-es5/fabricator.js:76:17)
    at /home/admin/MaxScale/_build/maxctrl/node_modules/pkg/lib-es5/fabricator.js:90:20
    at Socket.onError (/home/admin/MaxScale/_build/maxctrl/node_modules/pkg/lib-es5/fabricator.js:34:9)
    at Socket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at doWrite (_stream_writable.js:411:11)
    at writeOrBuffer (_stream_writable.js:399:5)
    [... lines matching original stack trace ...]
    at Socket.emit (events.js:198:13)
```

The binaries that were fetched seem to be the correct ones: `fetched-v10.24.1-linux-arm64`

**Comment by robertsLando** [comment] 2021-05-04 06:23
cc @jesec @erossignon

**Comment by markus456** [comment] 2021-05-04 10:37
I think I'll have to assume that the problem is with the glibc version the nodejs binaries are linked against. For example on CentOS 7 the build fails the same way but on CentOS 8 the build succeeds. With the x86_64 versions of the binaries we haven't seen problems like this.

**Comment by jesec** [comment] 2021-05-04 17:17
See vercel/pkg-fetch#124 . We use cross toolchain that comes with Ubuntu 18.04 to cross compile for arm64, while we use RHEL 7 toolchain to compile for x86_64. Unfortunately, that means the compatibility of arm64 binary is going to be a bit narrower than x86_64 one. However, the toolchain is the best one we have, as we don't have native arm64 machines.

**Comment by jesec** [comment] 2021-05-04 17:24
While the error message is the same, the issue reported by @markus456 is very different from the issue reported by @Deilan . And the issue reported by @adonespitogo is an entirely different one. 

Note that we have dropped support for 32-bit x86 in v5, so the original issue here can't possibly be relevant now. 

I am closing this issue, as things are very messy here. Please open a new one with new logs if necessary.

**Closed by jesec** 2021-05-04 17:24 UTC

**Comment by markus456** [comment] 2021-05-04 18:54
Makes perfect sense, once the GLIBC errors started popping up I should've figured out why it was failing. I think the `--build` option will solve the problem for us since we're always building on native machines.

**Comment by TerryJoo** [comment] 2022-11-17 08:19
Who can help me? This is my failed case when build with prisma client.

```
> [debug] prebuild-install failed[C:\Users\NvirLabs_2022-0923\Projects\nestjs-template\node_modules\.prisma\client\query_engine-windows.dll.node]:
  spawnSync C:\Users\NvirLabs_2022-0923\Projects\nestjs-template\node_modules\pkg\node_modules\.bin\prebuild-install ENOENT
/snapshot/nestjs-template/node_modules/.prisma/client/runtime/edge-esm.js:98
`)}return await y,this._fetcher.request({document:B,clientMethod:o,typeName:T,dataPath:s,rejectOnNotFound:O,isList:S,rootField:h,callsite:a,args:n,engineHook:this._middlewares.engine.get(0),headers:f,transaction:g,unpacker:b,otelParentCtx:x,otelChildCtx:bt.active()})}get $metrics(){if(!this._hasPreviewFlag("metrics"))throw new we("`metrics` preview feature must be enabled in order to access metrics API");return this._metrics}_hasPreviewFlag(n){var o;return!!((o=this._engineConfig.previewFeatures)!=null&&o.includes(n))}}return u(t,"PrismaClient"),t}u(Fg,"getPrismaClient");var Dg=["$connect","$disconnect","$on","$transaction","$use","$extends"];function is(e,t){return typeof e!="object"?e:new Proxy(e,{get:(r,n)=>{if(!Dg.includes(n))return n===Rg?t==null?void 0:t.id:typeof r[n]=="function"?(...o)=>n==="then"?r[n](o[0],o[1],t):n==="catch"||n==="finally"?r[n](o[0],t):is(r[n](...o),t):is(r[n],t)}})}u(is,"transactionProxy");var Ng={findUnique:"findUniqueOrThrow",findFirst:"findFirstOrThrow"};function kg(e,t,r){if(e){let n=Ng[r],o=t?`prisma.${t}.${n}`:`prisma.${n}`,i=`rejectOnNotFound.${t!=null?t:""}.${r}`;ki(i,`\`rejectOnNotFound\` option is deprecated and will be removed in Prisma 5. Please use \`${o}\` method instead`)}}u(kg,"warnAboutRejectOnNotFound");d();p();m();var jg=new Set(["toJSON","asymmetricMatch",Symbol.iterator,Symbol.toStringTag,Symbol.isConcatSpreadable,Symbol.toPrimitive]);function $g(e){return new Proxy(e,{get(t,r){if(r in t)return t[r];if(!jg.has(r))throw new TypeError(`Invalid enum value: ${String(r)}`)}})}u($g,"makeStrictEnum");d();p();m();d();p();m();var TD=fl.decompressFromBase64;var export_findSync=void 0;var export_warnEnvConflicts=void 0;export{pt as DMMF,ft as DMMFClass,Ka as Debug,Ge as Decimal,_t as Engine,Fs as Extensions,$t as MetricsClient,et as NotFoundError,_e as PrismaClientInitializationError,je as PrismaClientKnownRequestError,Qe as PrismaClientRustPanicError,Ce as PrismaClientUnknownRequestError,we as PrismaClientValidationError,pe as Sql,tf as Types,TD as decompressFromBase64,dd as empty,export_findSync as findSync,Fg as getPrismaClient,md as join,Qi as makeDocument,$g as makeStrictEnum,Ko as objectEnumValues,tc as raw,rc as sqltag,Ic as transformDocument,Yi as unpack,export_warnEnvConflicts as warnEnvConflicts};
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         


SyntaxError: Unexpected token 'export'
    at new Script (node:vm:102:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (node:events:537:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v18.5.0
/snapshot/nestjs-template/node_modules/.prisma/client/runtime/edge-esm.js:98
`)}return await y,this._fetcher.request({document:B,clientMethod:o,typeName:T,dataPath:s,rejectOnNotFound:O,isList:S,rootField:h,callsite:a,args:n,engineHook:this._middlewares.engine.get(0),headers:f,transaction:g,unpacker:b,otelParentCtx:x,otelChildCtx:bt.active()})}get $metrics(){if(!this._hasPreviewFlag("metrics"))throw new we("`metrics` preview feature must be enabled in order to access metrics API");return this._metrics}_hasPreviewFlag(n){var o;return!!((o=this._engineConfig.previewFeatures)!=null&&o.includes(n))}}return u(t,"PrismaClient"),t}u(Fg,"getPrismaClient");var Dg=["$connect","$disconnect","$on","$transaction","$use","$extends"];function is(e,t){return typeof e!="object"?e:new Proxy(e,{get:(r,n)=>{if(!Dg.includes(n))return n===Rg?t==null?void 0:t.id:typeof r[n]=="function"?(...o)=>n==="then"?r[n](o[0],o[1],t):n==="catch"||n==="finally"?r[n](o[0],t):is(r[n](...o),t):is(r[n],t)}})}u(is,"transactionProxy");var Ng={findUnique:"findUniqueOrThrow",findFirst:"findFirstOrThrow"};function kg(e,t,r){if(e){let n=Ng[r],o=t?`prisma.${t}.${n}`:`prisma.${n}`,i=`rejectOnNotFound.${t!=null?t:""}.${r}`;ki(i,`\`rejectOnNotFound\` option is deprecated and will be removed in Prisma 5. Please use \`${o}\` method instead`)}}u(kg,"warnAboutRejectOnNotFound");d();p();m();var jg=new Set(["toJSON","asymmetricMatch",Symbol.iterator,Symbol.toStringTag,Symbol.isConcatSpreadable,Symbol.toPrimitive]);function $g(e){return new Proxy(e,{get(t,r){if(r in t)return t[r];if(!jg.has(r))throw new TypeError(`Invalid enum value: ${String(r)}`)}})}u($g,"makeStrictEnum");d();p();m();d();p();m();var TD=fl.decompressFromBase64;var export_findSync=void 0;var export_warnEnvConflicts=void 0;export{pt as DMMF,ft as DMMFClass,Ka as Debug,Ge as Decimal,_t as Engine,Fs as Extensions,$t as MetricsClient,et as NotFoundError,_e as PrismaClientInitializationError,je as PrismaClientKnownRequestError,Qe as PrismaClientRustPanicError,Ce as PrismaClientUnknownRequestError,we as PrismaClientValidationError,pe as Sql,tf as Types,TD as decompressFromBase64,dd as empty,export_findSync as findSync,Fg as getPrismaClient,md as join,Qi as makeDocument,$g as makeStrictEnum,Ko as objectEnumValues,tc as raw,rc as sqltag,Ic as transformDocument,Yi as unpack,export_warnEnvConflicts as warnEnvConflicts};
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         


SyntaxError: Unexpected token 'export'
    at new Script (node:vm:102:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (node:events:537:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
    ```
