### ISSUE TITLE
Error `Cannot read file, ENOENT node:util` while trying to make a binary of a Typescript + NodeJS app with pkg

### ISSUE THREAD

**Issue by raaowx** [vercel/pkg#1363] opened 2021-11-09 11:37 UTC
### Objetive

I'm trying to pack into a binary a Typescript app and the NodeJS executable. I want to be able to distribute the binary in order to avoid to the users the task of installing Node, the dependencies, etc.

### Environment

* Typescript v4.4.4
* NodeJS v16.13.0
* [pkg](https://www.npmjs.com/package/pkg) v5.4.1

### What I'm doing?

1.- Compile the Typescript to Javascript. The `tsconfig.json` looks like:

>  _This step works fine_

```json
{
  "compilerOptions": {
    // Type Checking
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "alwaysStrict": true,
    "exactOptionalPropertyTypes": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noPropertyAccessFromIndexSignature": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "useUnknownInCatchVariables": true,
    // Modules
    "baseUrl": "src",
    "module": "ES2020",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "rootDir": "src",
    // Emit
    "declaration": true,
    "declarationDir": "types",
    "declarationMap": true,
    "importsNotUsedAsValues": "preserve",
    "newLine": "lf",
    "noEmitOnError": true,
    "outDir": "distribution",
    "preserveConstEnums": true,
    "sourceMap": true,
    // Javascript Support
    "allowJs": true,
    "checkJs": true,
    // Interop Constraints
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    // Language & Environment
    "lib": [
      "ES5",
      "ES6",
      "ES7",
      "ES2017",
      "ES2018",
      "ES2019",
      "ES2020",
      "ES2021",
    ],
    "target": "ES2021",
    // Compiler Diagnostics
    "listEmittedFiles": true,
    // Output Formatting
    "noErrorTruncation": true,
    // Completeness
    "skipLibCheck": true,
  },
  "include": [
    "src/**/*",
  ],
  "exclude": [
    "node_modules/**/*",
    "distribution/**/*",
    "types/**/*",
    "binaries/**/*",
  ]
}
```

2.- Try to pack NodeJS and the Javascript files into a binary using [pkg](https://www.npmjs.com/package/pkg). For this step, I execute the following command line:

```bash
pkg --out-path binaries .
```

> _This step fails_

The output of that line is the following error:

```bash
> pkg@5.4.1
> Targets not specified. Assuming:
  node16-linux-x64, node16-macos-x64, node16-win-x64
> Error! Cannot read file, ENOENT
  node:util
```

That command line is executed from the root of the project. `pkg` successfully find the `package.json` so it knows where to go to search the first file to start reading. The `package.json` looks like:

```json
{
  "name": "foo",
  "version": "4.0.0",
  "description": "bar moo",
  "homepage": "https://github.com/XXX/YYYY#readme",
  "bugs": {
    "url": "https://github.com/XXX/YYYY/issues"
  },
  "license": "MIT",
  "author": {
    "name": "XXX"
  },
  "main": "distribution/main.js",
  "bin": "distribution/main.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/XXX/YYYY.git"
  },
  "scripts": {
    "start": "node distribution/main.js",
    "clean": "rimraf node_modules distribution types binaries",
    "build": "npm ci && npm run compile",
    "compile": "tsc -p tsconfig.json"
  },
  "dependencies": {
    "axios": "^0.24.0",
    "cheerio": "^1.0.0-rc.10",
    "os-locale": "^6.0.1",
    "yargs": "^17.2.1"
  },
  "devDependencies": {
    "@types/cheerio": "^0.22.30",
    "@types/yargs": "^17.0.5"
  },
  "engines": {
    "node": ">=16.0.0"
  },
  "private": true,
  "type": "module"
}
```

### Questions

* How to get rid of the error?
* Am I missing something?

**Comment by mallardduck** [comment] 2021-11-17 21:56
Having the same type of issue here - both using typescript and the `node:` protocol to import builtin modules.

Looking at the history of the `node:` protocol it seems that it was introduced in `v16.0.0` and `v14.18.0` - depending on if using ESM or CommonJS. Not sure if that's related to why this isn't working with `pkg` though.

**Comment by mallardduck** [comment] 2021-11-18 00:09
@raaowx - assuming that you're trying to use pkg on the compiled TS then I think this isn't specific to typescript being used. Rather I think it seems this is a duplicate of: https://github.com/vercel/pkg/issues/1309

**Closed** 2021-11-24 21:37 UTC
