### ISSUE TITLE
Is there any way to package instead for node_modules?

### ISSUE THREAD

**Issue by KuoKongQingYun** [vercel/pkg#659] opened 2019-04-07 22:18 UTC
I have two executes using almost same node modules,so I want to share the node_modules in order to reduce the total size.
but when using pkg to package the two executes,it package node_modules twice equivalently.
so is there any way to package instead for node_modules?

**Comment by hipstersmoothie** [comment] 2021-03-23 17:12
duplicate of #559

**Closed by hipstersmoothie** 2021-03-23 17:12 UTC
