### ISSUE TITLE
Pkg with ncc

### ISSUE THREAD

**Issue by evandikt** [vercel/pkg#1137] opened 2021-04-16 12:24 UTC
Hey :)

In a project I use ncc with pkg.
I have a little problem, I thought it was coming from ncc but no it's coming from pkg !

I link my issue here ...

https://github.com/vercel/ncc/issues/650

thx :+1:

**Comment by robertsLando** [comment] 2021-04-16 13:24
Duplicate of #1135

**Closed by robertsLando** 2021-04-16 13:24 UTC
