### ISSUE TITLE
logging not replacing variables

### ISSUE THREAD

**Issue by JoshMcCullough** [vercel/pkg#630] opened 2019-02-12 21:47 UTC
https://github.com/zeit/pkg/blob/2faf045f6e615aa188f92434100158610747b651/lib/walker.js#L112

Variable replacement is not occurring here (line 110 and 112). Log output is literally ...

>Content of %1 is added to queue. It was required from %2

Edit: this is happening all over the log.

**Comment by JoshMcCullough** [comment] 2021-04-07 12:08
Might no longer be an issue, not sure.

**Comment by robertsLando** [comment] 2021-04-07 12:09
@joecohens Could you try again to see if this is fixed?

**Comment by leerob** [comment] 2021-04-07 12:18
Is there a reason you tagged Joe?

**Comment by robertsLando** [comment] 2021-04-07 13:09
No idea why github tagged him I used the first tagged person I found in the dropdoown that is usually the correct one 😆 Fixed now

**Comment by jesec** [comment] 2021-05-14 15:12
```
> [debug] Content of /home/jc/flood/node_modules/path-is-absolute/package.json is added to queue. It was required from /home/jc/flood/node_modules/glob/sync.js
```

Can't reproduce. Please let me know if the issue is still relevant.

**Closed by jesec** 2021-05-14 15:12 UTC
