### ISSUE TITLE
Fail in deploy

### ISSUE THREAD

**Issue by eduar2** [vercel/pkg#763] opened 2019-09-03 22:54 UTC
If I test locally (pkg . or with any option), it works correctly, but when I deploy to a server I have the next errors: 

ERROR in ./node_modules/pkg/prelude/bootstrap.js
Module not found: Error: Can't resolve 'internal/module' in '/home/eduar2/Documentos/Dreamcode/icommander/corserva-icommander/backend-services/node_modules/pkg/prelude'
 @ ./node_modules/pkg/prelude/bootstrap.js 1206:9-35
 @ ./node_modules/pkg/lib-es5/packer.js
 @ ./node_modules/pkg/lib-es5/index.js
 @ ./src/agent/agent.service.ts
 @ ./src/agent/agent.module.ts
 @ ./src/app.module.ts
 @ ./src/lambda.ts

ERROR in ./node_modules/pkg/prelude/bootstrap.js
Module not found: Error: Can't resolve 'internal/modules/cjs/helpers' in '/home/eduar2/Documentos/Dreamcode/icommander/corserva-icommander/backend-services/node_modules/pkg/prelude'
 @ ./node_modules/pkg/prelude/bootstrap.js 1215:9-48
 @ ./node_modules/pkg/lib-es5/packer.js
 @ ./node_modules/pkg/lib-es5/index.js
 @ ./src/agent/agent.service.ts
 @ ./src/agent/agent.module.ts
 @ ./src/app.module.ts
 @ ./src/lambda.ts

ERROR in ./node_modules/pkg/prelude/bootstrap.js
Module not found: Error: Can't resolve 'internal/util' in '/home/eduar2/Documentos/Dreamcode/icommander/corserva-icommander/backend-services/node_modules/pkg/prelude'
 @ ./node_modules/pkg/prelude/bootstrap.js 1461:30-54
 @ ./node_modules/pkg/lib-es5/packer.js
 @ ./node_modules/pkg/lib-es5/index.js
 @ ./src/agent/agent.service.ts
 @ ./src/agent/agent.module.ts
 @ ./src/app.module.ts
 @ ./src/lambda.ts

ERROR in ./node_modules/pkg/prelude/bootstrap.js
Module not found: Error: Can't resolve 'worker_threads' in '/home/eduar2/Documentos/Dreamcode/icommander/corserva-icommander/backend-services/node_modules/pkg/prelude'
 @ ./node_modules/pkg/prelude/bootstrap.js 48:31-56
 @ ./node_modules/pkg/lib-es5/packer.js
 @ ./node_modules/pkg/lib-es5/index.js
 @ ./src/agent/agent.service.ts
 @ ./src/agent/agent.module.ts
 @ ./src/app.module.ts
 @ ./src/lambda.ts

**Comment by hipstersmoothie** [comment] 2021-03-24 23:11
No reproduction repo and it's been a year since updates. Closing, feel free to open a new issue with a reproduction repo if the problem still exists!

**Closed by hipstersmoothie** 2021-03-24 23:11 UTC
