### ISSUE TITLE
es6 modules

### ISSUE THREAD

**Issue by x8core** [vercel/pkg#926] opened 2020-06-03 11:21 UTC
Hi! What about to pkg of an app that use es6 modules? Is pkg correctly works with such apps?

**Comment by marcj** [comment] 2020-06-11 01:26
Yes

**Comment by luxferresum** [comment] 2020-06-16 14:13
It seems not to work for me:
```
SyntaxError: Unexpected token export
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\app\dist\src\tools\deps-resolver.js:772
export function resolveDeps(detBundles) {
^^^^^^

```

**Comment by pedrohenriquebr** [comment] 2020-06-18 20:00
Maybe using Babel will works

**Comment by luxferresum** [comment] 2020-06-18 22:20
sure, I could transform to AMD or common.js. But thats not the point here. Native ESM does *not* work.

**Comment by Daniel-Olivier** [comment] 2020-06-23 05:27
Which version of Node JS are you targeting when building your project?

**Comment by noguilty4you** [comment] 2020-09-24 11:33
@Daniel-Olivier Hi, I had some issue with {type: module} and .mjs/.js files. Node version was 14.4, pkg target was `node14-alpine-x64`

**Comment by KaoSDlanor** [comment] 2020-09-25 05:00
Hi @noguilty4you

Are you experiencing the exact same issue and receiving `SyntaxError: Unexpected token export` errors?

**Comment by Daniel-Olivier** [comment] 2020-09-25 05:02
Hi @noguilty4you

Are you experiencing the exact same issue and receiving SyntaxError: Unexpected token export errors?

**Comment by noguilty4you** [comment] 2020-09-25 18:00
@Daniel-Olivier, yes. Yesterday I refactored the whole project to using commonjs modules and so I have no problems =(

**Comment by MichaelKorn** [comment] 2020-12-16 12:29
I took a look at the situation, especially since several open issues are related to es6 modules.
es6 modules are not supported!

1. The caching cannot work like this:
https://github.com/vercel/pkg/blob/52b4933aeab3acaddbe4884aef8ee5f127e4a468/lib/fabricator.js#L20-L25
1.1. vm.Script is just for CommonJS modules. For ECMAScript modules [vm.Modules](https://nodejs.org/api/vm.html#vm_class_vm_module) and [vm.SourceTextModule](https://nodejs.org/api/vm.html#vm_class_vm_sourcetextmodule) have be be used.
1.2. node must be run with `--experimental-vm-modules`
2. ECMAScript modules can not be started within the output file (eg. .exe) , because only CommonJS is considered in https://github.com/vercel/pkg/blob/master/prelude/bootstrap.js
2.1 In particular, _load() is a [legacy way](https://github.com/nodejs/node/blob/0b3caadad378e4ed9352a6ec5aba3dc080889467/lib/internal/modules/run_main.js#L66-L78) to run CommonJS modules: https://github.com/vercel/pkg/blob/52b4933aeab3acaddbe4884aef8ee5f127e4a468/prelude/bootstrap.js#L1378-L1381

**Comment by hipstersmoothie** [comment] 2021-03-25 00:02
closing duplicate of #782

**Closed by hipstersmoothie** 2021-03-25 00:02 UTC
