### ISSUE TITLE
give error with app-module-path

### ISSUE THREAD

**Issue by RezaErfani67** [vercel/pkg#724] opened 2019-06-23 05:23 UTC
how can i use it with [app-module-path](https://www.npmjs.com/package/app-module-path)?
it gives error: 
can not find module ....

**Comment by hipstersmoothie** [comment] 2021-03-24 23:17
No reproduction repo and it's been a year since updates. Closing, feel free to open a new issue with a reproduction repo if the problem still exists!

**Closed by hipstersmoothie** 2021-03-24 23:17 UTC
