### ISSUE TITLE
Code can be leaked

### ISSUE THREAD

**Issue by I2rys** [vercel/pkg#1392] opened 2021-11-11 01:51 UTC
### What version of pkg are you using?

4.5.1

### What version of Node.js are you using?

v14.17.5

### What operating system are you using?

Windows

### What CPU architecture are you using?

x64 & x86

### What Node versions, OSs and CPU architectures are you building for?

node14-win-x86, node14-win-x64, node14-linux, node14-macos

### Describe the Bug

I don't think this really is a bug but it can cause a code leakage and can be fatal If your planning to use PKG for your business or paid softwares & etc, the bug here is that PKG doesn't really compile your code/hide it where It is hard to find like when your compiling your C++ code.

### Expected Behavior

PKG should also include your code in compiling in others word hide it, It should work like compiling a C++, GO code & etc. It should not place your code in plain site where it can be leaked.

### To Reproduce

1.Compile your index.js in the Oss and CPU architectures I specified.
2.Open the compiled file in any IDE's or softwares that can read files(Notepad++, VSCode).
3.Get any code in the uncompiled index.js and find it on the compiled file, you will see that the index.js code is in plain site.

**Comment by jesec** [comment] 2021-11-12 07:47
Dupe of #1368.

**Closed by jesec** 2021-11-12 07:47 UTC
