### ISSUE TITLE
Error spawn ENOENT when an imported module inside the application spawns an *.exe 

### ISSUE THREAD

**Issue by rohit5ram** [vercel/pkg#342] opened 2018-02-02 12:05 UTC
Hi @igorklopov ,

I am using [desktop-screenshot](https://github.com/johnvmt/node-desktop-screenshot) in my application.
When I packaged my application, pkg couldn't include the desktop-screenshot js files as it has a non-literal argument in require. I have included it in my application package.json as 

`"pkg": {
    "assets": [
      "node_modules/desktop-screenshot/capture/bin/scrot/scrot",
      "node_modules/desktop-screenshot/capture/bin/nircmd.exe"
    ],
    "scripts": [
      "node_modules/desktop-screenshot/capture/*.js"
    ]
  }`
From pkg build logs, I found that it included everything.

This line of code from desktop-screenshot(/capture/win32.js)

`var nircmd = childProcess.spawn(path.join(__dirname, "bin", "nircmd.exe"), ["savescreenshot", options.output]);` 

fails in error 

Error: spawn C:\snapshot\myapp\node_modules\desktop-screenshot\capture\bin\nircmd.exe ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

I am facing the same issue with another dependency [dialog-node](https://github.com/bat-tomr/dialog-node) as well. Looks like there is an issue in the way the paths are handled from inside the executable.

@bat-tomr is helping for a workaround on the same issue [#1](https://github.com/bat-tomr/dialog-node/issues/1)

Can you please help me out in solving this?

**Comment by ccc-tomr** [comment] 2018-02-04 02:34
My two cents...

It looks like pkg.js does not allow OS tools to access assets within executables created by pkg.js (at least I did not find a way). 

Example:

code snippet from index.js:
```
  var process = spawn('/bin/bash', ['-c', 'test.sh']
```

If index.js is called by 'nodejs index.js' it works, but if it is packaged using pkg.js (index.js and test.sh), this will fai. /bin/bash can't find test.sh because it is within pkg.js' snapshot filesystem and this filesystem is not accessible from outside the package, therefore bash can't access it.

In order to allow such a use case, pkg.js would need to be extended to allow for the deployment of some assets outside the generated executable. This would make pkg.js more of a packaging tool rather than a tool to generate executables from your nodejs projects. 

My opinion: I think pkg.js is a great tool to create executables out of nodejs projects but it is not a packaging tool as the name suggests. For proper packaging other tools like msi, NSIS, dpkg-deb, fpm,... should probably be used. In my opinion, it is perfectly fine to use one tool to generate executables and another tool to package. My only critic would be that a different project name than pkg.js would be less misleading.

**Comment by curtgrimes** [comment] 2018-02-18 08:20
I just experienced something similar when trying to run [ngrok](https://github.com/bubenshchykov/ngrok). The dirty fix I'm using right now is to have a copy of ngrok.exe outside of the executable created by pkg, and then in [ngrok's index.js](https://github.com/bubenshchykov/ngrok/blob/66ce776e7ab66b38f1d49b600f71379ba793610e/index.js#L113) instead of this:

```
ngrok = spawn(
		bin,
		start,
		{cwd: dir});
```

I'm doing this:

```
ngrok = spawn(
		path.join(process.cwd(), "ngrok.exe"),
		start);
```

**Comment by micooz** [comment] 2018-02-25 11:58
Hey guys, I just found a workaround here. In order to make syscalls(like spawn) work on pkg.js' snapshot filesystem, we can just `copy` our assets to disk, then access them outside of snapshot filesystem:

```js
const source = path.join(__dirname, 'foo.exe');
const target = path.join('somewhere/foo.exe');

fs.copyFileSync(source, target); // ENOENT
child_process.spawn(target);
```

However, this will not work because `fs.copyFileSync()` made another syscall: `copyfile`, it cannot find `source` inside of snapshot filesystem.

But, instead of using `copyFileSync`, we can **read** assets into memory then **write** them into disk:

```js
const fs = require('fs');
const utils = require('util');

const copyFile = utils.promisify(fs.copyFile);
const chmod = utils.promisify(fs.chmod);

async function copy(source, target) {
  if (process.pkg) {
    // use stream pipe to reduce memory usage
    // when loading a large file into memory.
    fs.createReadStream(source).pipe(fs.createWriteStream(target));
  } else {
    await copyFile(source, target);
  }
}

const source = path.join(__dirname, 'foo.exe');
const target = path.join('somewhere/foo.exe');

await copy(source, target); // this should work
await chmod(target, 0o765); // maybe need to grant execute permission

child_process.spawn(target);
```

**Comment by bat-tomr** [comment] 2018-02-25 16:59
I like Micooz approach, although it might not be practical when the required assets are large. To read required assets in memory and then write them to disk every time the pkg created binary is called would delay the start of the binary , especially if those required assets are large. 

For now, I am going to stick with my current approach:
- use pkg.js to create a binary
- use a proper packaging tool (NSIS, dpkg-deb, fpm) to create an installer

**Comment by s-h-a-d-o-w** [comment] 2018-05-04 10:31
Personally, I find all proposed solutions not acceptable because... what if you're referring not simply to a single executable but that executable within its environment?
Take e.g. wmic in Windows. Its executable is in a directory along with a whole bunch of dlls.
I guess one could package all of that into an installer but... why? They presumably exist on every Windows installation.

And this doesn't seem like a novel idea - you can usually spawn whatever is globally available without having to distribute it along with your executable? (Not talking about node here but also Python, C++, etc.)

**Comment by s-h-a-d-o-w** [comment] 2018-05-06 19:06
Found a workflow for me based on the following observations. Feel free to correct me. (Might be worth dedicating a chapter in the README about how the spawning of processes can be handled?)

- Executing anything outside actually works as expected as long as you either omit cwd or specify an absolute path outside the snapshot file system. One option mentioned above is process.cwd(). (No using of `__dirname` anywhere in the call to spawn!)

- No spawning of anything within snapshot file system possible:

```
> [debug] The file was included as asset content
  D:\development\github\spotify-ad-blocker\node_modules\wmi-client\lib\cmd.exe

 [...]

Error: spawn D:\snapshot\spotify-ad-blocker\node_modules\wmi-client\lib\cmd.exe ENOENT
```

- If the external executable needs assets from your "bundle", you will have to copy them to the regular file system (see https://github.com/zeit/pkg/issues/342#issuecomment-368303496). I think %APPDATA% is a decent candidate.

So what I've done myself is spawning wmic by using process.cwd() as cwd, essentially:
```
    spawn('wmic', args, {
        cwd: process.cwd(),
    });
```
And for testing purposes, I copied an asset required for wmic from the snapshot file system to %TEMP% using the method @micooz posted. Works just fine.

**Comment by zwhitchcox** [comment] 2018-07-29 20:21
so, @s-h-a-d-o-w has provided a great fix for the typical use, but it does not work for my use case, where the spawned process relies on `__dirname`, not the cwd to run the executable. The only fix I can think of would be to create a webpack loader that dynamically replaces `__dirname` with the directory relative to the `process.cwd()`, but that seems less than ideal. Does anyone else have any other suggestions for when `process.cwd()` won't be reliable to create the path to the executable, for instance, when the executable is within a `node_modules` folder?

**Comment by s-h-a-d-o-w** [comment] 2018-07-29 20:50
What you're describing I think is something I'm doing this with one of the dependencies in one of my projects - search for "tray_windows_release.exe" here: https://github.com/s-h-a-d-o-w/spotify-ad-blocker/blob/v2.0.0/package.json
The following workflow is related to this:
https://github.com/zeit/pkg/issues/329#issuecomment-398151429

Essentially, whatever binary you want to spawn (whether native addon or regular executable), you have to extract it from the snapshot file system to the user's file system yourself.
If following the same directory structure is an option for you (meaning - you recreate the same path towards the executable as it exists in your dev environment), then `process.cwd()` should work.
(If you want to extract them somewhere else though, like maybe %TEMP%, see the workflow that I just linked to above)

**Comment by zwhitchcox** [comment] 2018-07-30 16:59
Ok, so, I just ended up duplicating the original maintainer's project, because it's not that big, and I don't really want to have it outside the project. Thanks!

**Comment by zwhitchcox** [comment] 2018-07-30 17:04
So, just out of interest, when I tried to create a directory outside of the project and then require, so,

`fs.copy('node_modules/clipboardy', 'c:/Program Files/clipboardy')`,

and then include it in my project, `require('c:/Program Files/clipboardy')`, I got an error, and even when I just copied it directly to the `c:` directory. Is this not possible? It seems like `pkg` bootstraps the `require` function, but does it provide the old `require` as well somewhere?

**Comment by stepankuzmin** [comment] 2018-09-20 10:51
Hi there! I've the same issue with `osrm` native modules. So there is no simpler way to spawn process from assets now?

**Comment by LinkTree3** [comment] 2018-09-25 18:58
@zwhitchcox Hi ,did you manage to solve the issue with using clipboard within pkg? I am facing the same issue right now.

**Comment by PatelAshish1** [comment] 2019-11-08 16:28
NOTE: This error is almost always caused because the command does not exist, because the working directory does not exist, or from a windows-only bug. I found a particular easy way to get the idea of the root cause of:

Error: spawn ENOENT
The problem of this error is, there is really little information in the error message to tell you where the call site is, i.e. which executable/command is not found, especially when you have a large code base where there are a lot of spawn calls. I found a very easy way to spot which command cause the problem rather than adding event listeners everywhere in your code as suggested in @laconbass’ answer. The key idea is to wrap the original spawn call with a wrapper which prints the arguments send to the spawn call. Here is the wrapper function, put it at the top of the index.js or whatever your server’s starting script.

Find Full Code At [Here](https://icetutor.com/question/how-do-i-debug-error-spawn-enoent-on-node-js/)

**Comment by Honest-Objections** [comment] 2020-04-20 10:48
A quick dirty module based off @micooz answer: 

``` javascript
const fs = require('fs');
const glob = require('glob');
const path = require('path'); 
const utils = require('util');
const package = require('./package.json');
const copyFile = utils.promisify(fs.copyFile);


var isPackaged = process.execPath.search(/node.*/) == -1; 
var basePath = isPackaged ? path.dirname(process.execPath) : __dirname; 

module.exports = {
    isPackaged: isPackaged,
    path: function (source) {
        if (!isPackaged) return source; 

        var pattern = /.*[/\\]snapshot[/\\][^/\\]*/i
        return path.join(basePath, source.replace(pattern, '')); 
    },
    copy: function (source, target = null) {

        // retain current folder structure
        if (!target) target = this.path(source); 

        // create target
        fs.promises.mkdir(path.dirname(target), { recursive: true }).then(() => {
            return fs.createReadStream(source).pipe(fs.createWriteStream(target)); 
        }).catch((err) => {
            console.log('Could not make ', target, ':', err); 
        });

    },
    export: function () {
        var self = this; 
        if (self.isPackaged) {
            package.pkg.assets.forEach(asset => {
                glob(asset, { nodir: true }, function (er, files) {
                    files.forEach(file => self.copy( path.join(__dirname, file) ));
                })
            });
        }
    }
}
```

This will automatically copy all the files explicitly included through the `package.json` `pkg.assets` array into `path.dirname(process.execPath)`, retaining it's hierarchy. 

```javascript
assets = require('./asset-export.js');

assets.export(); // do once at the start of your application

// anytime you want to reference an asset...
var broken = path.join(__dirname, 'my.exe');
var fixed = assets.path( broken ); 
``` 

No shortage of improvements, but it works for what I need. I'm not familiar enough with the inner working of pkg to think of a suitable proper solution. I also agree with @ccc-tomr that this may be out of scope for pkg. 

It would be good to get this issue addressed on the readme.

**Comment by vincss** [comment] 2020-05-15 15:12
Hi there !
It's a bit old now, but, did someone found a proper fix ?

**Comment by LeonardoRick** [comment] 2021-02-08 21:42
Hi, following here because I'm very interested o a proper solution for this case too

**Comment by brazzmo** [comment] 2021-04-09 22:38
Any updates to this? 

Would be awesome to not have to use workarounds for this.

**Comment by robertsLando** [comment] 2021-04-11 09:34
This is not an issue. In order to fix this you should check if you app is running with pkg or not (check if `process.pkg` is true) based on this you have to defined the correct `cwd` options in the `spawn` call: https://github.com/vercel/pkg#snapshot-filesystem

**Closed by robertsLando** 2021-04-11 09:34 UTC

**Comment by kybarg** [comment] 2021-12-30 19:29
@robertsLando could you please bring some light here?
so when running from internal file system, what `cwd` sould be set?

**Comment by kaichaosun** [comment] 2022-01-17 13:44
Still got this issue, copy snapshot files into os file system is not ideal, any alternative or plan to add this feature?

**Comment by otanim** [comment] 2022-11-16 22:42
Apparently, I found the same "solution" that @micooz suggested, but on Linux system:

**Case scenario:**
I needed to include an executable file `hello_world` as an asset into `/snapshot/project/bin/hello_world` virtual path and based on some conditions execute it inside the Linux environment.

**The problem:**
I was getting the following error when I've been trying to execute the command via `child_process.spawn`:
```
/bin/sh: 1: /snapshot/project/bin/hello_world: not found
```
So clearly my OS is trying to execute `hello_world` command via `/bin/sh`, however, the system is unable to access to `/snapshot` virtual filesystem, therefor not able to execute it.

**The workaround:**
Clearly, the main file system is unable to access the virtual file system, but we can do the opposite, by copying our executable file from the virtual file system into the main file system and executing it from there, basically, this is what I did:
```javascript
//node packages
const fs = require('fs');
const os = require('os');
const path = require('path');
const {execSync, spawn} = require('child_process');

// executable file name
const executable = 'hello_world';

//file path to the asset executable file
const remoteControlFilePath = path.join(__dirname, `../bin/${executable}`);

let executableFileFullPath = remoteControlFilePath;
// avoid the workaround if the parent process in not pkg-ed version.
if (process.pkg) {
  // creating a temporary folder for our executable file
  const destination = fs.mkdtempSync(`${os.tmpdir()}${path.sep}`);
  const destinationPath = path.join(destination, executable);
  executableFileFullPath = destinationPath;
  // copy the executable file into the temporary folder
  fs.copyFileSync(remoteControlFilePath, destinationPath);

  // on Linux systems you need to manually make the file executable
  execSync(`chmod +x ${destinationPath}`);
}

// using {detached: true}, execute the command independently of its parent process
// to avoid the main parent process' failing if the child process failed as well.
const child = spawn(executableFileFullPath, {detached: true});
child.stdout.on('data', (data) => {
  console.log(`child stdout:\n${data}`);
});
child.stderr.on('data', (data) => {
  console.error(`child stderr:\n${data}`);
});
child.on('exit', (code, signal) => {
  console.log(`child process exited with code ${code} and signal ${signal}`);
});
```

**Comment by sunknudsen** [comment] 2023-07-19 20:00
Hey @otanim, thanks for sharing recipe!

Did you (or anyone else) manage to find a workaround that doesn’t involve copying binaries using `tmpdir`?
