### ISSUE TITLE
Getting timeout error when stopping exe running as Service with nssm

### ISSUE THREAD

**Issue by slmmm** [vercel/pkg#140] opened 2017-06-16 22:24 UTC
I was able to easily create my exe using pkg.  I then used nssm (https://nssm.cc/usage) to create and run my exe as a Windows Service.

Unfortunately, when I try to Stop the service, it results in a Windows error 1053 (service did not respond in a timely manner).  
nssm has four stages it uses to shut down the application, and by default it attempts all four in order of CONTROL-C event first, WM_CLOSE message, WM_QUIT message, and lastly a TerminateProcess() to Windows OS.
I expected the CONTROL-C would work since this is successful method when running the exe in CLI.  

Has anyone else had similar issue and resolved it?

**Comment by slmmm** [comment] 2017-06-23 17:05
Hi Igor,
Thank you for reviewing this issue.
I was wondering if you might have a possible guess at when a patch might be available?
For now, we are having to cure the hang-up after the Stop command by killing the process manually.

**Comment by Neolo** [comment] 2019-10-28 07:57
It's indeed sucking Service Manager, because it's been 2 years and it still doesn't stop properly.

**Comment by hipstersmoothie** [comment] 2021-03-23 16:54
duplicate of #137

**Closed by hipstersmoothie** 2021-03-23 16:54 UTC
Labels: bug, patch

**Comment by introspection3** [comment] 2023-11-03 02:49
there is something wrong with pkg
